### ISSUE TITLE
Problems with provider

### ISSUE THREAD

**Issue by OskyEdz** [eatonc/actual-gcp#3]
I've followed your guide step-by-step.
But I probably have forgotten something that is isn't explicitly mentioned.

I get the following error when I run "terraform plan"
```
Waiting for the plan to start...

Terraform v1.9.8
on linux_amd64
Initializing plugins and modules...
╷
│ Error: Attempted to load application default credentials since neither `credentials` nor `access_token` was set in the provider block.  No credentials loaded. To use your gcloud credentials, run 'gcloud auth application-default login'
│
│   with provider["registry.terraform.io/hashicorp/google"],
│   on main.tf line 1, in provider "google":
│    1: provider "google" {
│
│ google: could not find default credentials. See
│ https://cloud.google.com/docs/authentication/external/set-up-adc for more
│ information
╵
Operation failed: failed running terraform plan (exit 1)
```

My main.tf looks like this:
```
provider "google" {
  project               = "key-chalice-xxxxxx-tx"
  region                = "us-central1"
  zone                  = "us-central1-c"
  user_project_override = true
  billing_project       = "key-chalice-xxxxxx-tx"
}
```

And I've made sure to run "gcloud auth application-default login" in the same shell just before.

I believe I might have to move my folders/files around, but I don't know where to place what.
I've noticed that the "%APPDATA%\gcloud\application_default_credentials.json" and I have the git clone under (userprofile)\Git\actual-gcp
I tried to add the "credentilas" line to main-tf but it did not understand my path/filename. Or otherwise complained it was not a JSON file at all.

I also have the same problem with the ssh key path. It will not recognized it's existences.

I also tried to place the files in the same folder as actual-gcp...

**Comment by OskyEdz** [comment]
I went with the solution here instead: https://github.com/eatonc/actual-gcp/issues/2#issuecomment-2441279280

**Comment by lleilin** [comment]
I had the same error. I fixed it by setting my terraform execution mode to be local by updating the workspace settings on app.terraform.io.

<img width="643" alt="image" src="https://github.com/user-attachments/assets/46679b54-0b25-4359-ba78-14e8d8d74fa0">

**Comment by vinnychan** [comment]
I ran into the same error and even went into the Google Cloud console to generate a new token key for the technical user. But then was still running into other errors like not being able to find my local ssh key even though it definitely exists. 

After poking around the GH issues to see if anyone else ran into these problems, I tried lleilin's solution above and it worked.

@eatonc maybe consider adding this step to the README as well?

**Comment by eatonc** [comment]
Thanks, @vinnychan and @lleilin. I thought calling out that the HCP Terraform workspace should be configured using the CLI Driven Workflow covered this, but perhaps not. I'll revisit it and update the documentation. Thanks for the feedback!

**Comment by eatonc** [comment]
@OskyEdz / @vinnychan  / @lleilin - I've updated the README to include checking/configuring the Execution Mode within HCP Terraform. Thanks again for the feedback!
